### ISSUE TITLE
IBackgroundProcess documentation?

### ISSUE THREAD

**Issue by StevenDevooght** [HangfireIO/Hangfire-Documentation#85]
In [Hangfire 1.5](https://github.com/HangfireIO/Hangfire/pull/454) the `IBackgroundProcess` interface was introduced.  We are currently working on a system where we need a process that is running throughout the lifetime of our application (hosted on IIS). The `IBackgroundProcess` seems the way to go, but there is nothing documented regarding that subject.

Is this actually a feature or should we stay away from it?

**Comment by StevenDevooght** [comment]
Apparently there `IBackgroundProcess` interface is briefly explained [here](https://www.hangfire.io/overview.html).

**Comment by demoran23** [comment]
`IBackgroundProcess` is used by `IApplicationBuilder.UseHangfireServer`.  It accepts a collection as an optional argument.

If not argument is provided, it will interrogate your DI container via `services.GetServices` to get any registrations you've made and use those.

So, to use this, register your implementation in your DI container.

**Comment by satma0745** [comment]
But what about the `IBackgroundProcessAsync` interface?

I've managed to register the `IBackgroundProcess` service in the DI and it's working fine, but I would prefer using an async version. When I drop-in replace `IBackgroundProcess` with `IBackgroundProcessAsync`, and keep all other code untouched, the process is never started (the service is not even instantiated).

It also looks like this issue has been around for quite some time: this almost 2yo post (https://discuss.hangfire.io/t/how-to-use-ibackgroundprocessasync-keeping-mailkit-alive/9984) mentions the same issue.
